set_property PACKAGE_PIN F14 [get_ports clk]
create_clock -period 10.000 -name gclk [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {angle[0]}]
set_property PACKAGE_PIN V2 [get_ports {angle[0]}]
set_property PACKAGE_PIN U2 [get_ports {angle[1]}]
set_property PACKAGE_PIN U1 [get_ports {angle[2]}]
set_property PACKAGE_PIN T2 [get_ports {angle[3]}]
set_property PACKAGE_PIN T1 [get_ports {angle[4]}]
set_property PACKAGE_PIN R2 [get_ports {angle[5]}]
set_property PACKAGE_PIN R1 [get_ports {angle[6]}]
set_property PACKAGE_PIN P2 [get_ports {angle[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports servo_sig]
set_property PACKAGE_PIN T6 [get_ports servo_sig]
set_property PACKAGE_PIN J2 [get_ports rst]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports RGB1];   
